### ISSUE TITLE
"ID" specification

### ISSUE THREAD

**Issue by antass** [pitagora-network/pitagora-cwl#6]
Thanks for making these workflows available to the community! I am just learning to build workflows using `cwl` and use your `*.cwl` and `*.yml` files as templates. In the `hisat2` workflow, I see multiple reference to the `"ID"` variable, but can't figure out where it is set.. Any hints?

**Comment by inutano** [comment]
Hi @antass, thanks for trying to use out workflows! Can you point the file you are trying to use, since we have multiple tools and workflows for hisat2? As I couldn't find `ID` input field in our files, it'd be helpful to assist you if you could show the debug output.

**Comment by antass** [comment]
Hi @inutano! I had been working with the `cwl/tools/samtools/samtools-sort.yml` file as part of the `hisat2` workflow. I just noticed the workflow has been updated in e1ab059328817ce9d6997932c5ece90ac6913cff 10 hours ago and `ID` is no longer referenced. It's awesome you have also added test files - I will work with the newly committed version and see how far I can get! Thanks!

**Comment by inutano** [comment]
Ah, that "ID" string in the yml file was used as a template which is converted to a real file name afterward. I've been refactoring the hisat2 workflows today, so there're many changes since you created this issue. Now I've separated the original `hisat2` workflow to `hisat2-cufflinks` and `hisat2-stringtie`, and now testing. The most stable workflow unit for now is one of `kallisto`, which also has a validated test script. Let me know if you had a trouble on running any of them!

**Comment by antass** [comment]
Oh cool! I was actually going to ask about a shell script to run the whole `hisat2-stringtie` workflow, as I know that's what I'll be working with and couldn't figure out how to utilize the individual tool shell scripts. Are you planning on writing those as well? In the meantime, I'll take a look at `kallisto` for some inspiration.

**Comment by antass** [comment]
Woah just noticed you already did that. Awesome! Thanks so much, this is extremely helpful.

**Comment by inutano** [comment]
Yeah this week I'm working to heavily refactor the CWL scripts originally developed by the other committer. The test scripts are now just for my testing environment, and should be modified so that anyone can run everywhere without configurations. And - Sorry! - the workflow files updated today had some errors, so I just fixed. At least `hisat2-stringtie` works now.

To perform `workflows/hisat2-stringtie/test/hisat2-stringtie_wf.sh`, it goes like this:

```
$ find . 
.
./se.test.id.list
./hg38
./hg38/genome.1.ht2
./hg38/genome.2.ht2
./hg38/genome.3.ht2
./hg38/genome.4.ht2
./hg38/genome.5.ht2
./hg38/genome.6.ht2
./hg38/genome.7.ht2
./hg38/genome.8.ht2
./gencode.v28.annotation.gtf
./download-sra.cwl
./pfastq-dump.cwl
./hisat2_mapping_se.cwl
./samtools_sam2bam.cwl
./samtools_sort.cwl
./stringtie_assemble.cwl
./hisat2-stringtie_wf_se.cwl
./hisat2-stringtie_wf_se.yml.sample
./hisat2-stringtie_wf.sh
$ bash hisat2-stringtie_wf.sh se.test.id.list ./hg38/genome.1.ht2 ./gencode.v28.annotation.gtf ./hisat2-stringtie_wf_se.cwl ./hisat2-stringtie_wf_se.yml.sample
```

You can get `se.test.id.list` from [here](https://github.com/pitagora-galaxy/cwl/tree/master/test/data), hisat2 reference data is available on [its project page](https://ccb.jhu.edu/software/hisat2/manual.shtml), and the gencode annotation file [here](https://www.gencodegenes.org/releases/current.html). Rest of the files are in the repo, so you can give it a try, see logs how it works, then modify the input or the script to pass the IDs you want to analyze, or your own sequence data.

Again, more heavy updates are coming on this week, so the scripts may change - but I'm sure they will get better :) Feel free to contact me here!

**Comment by antass** [comment]
Wow, you are reading my mind! Was again just about to ask about the format of the input id file. This is going to be super useful for other noobs like me. I tested the workflow and it all worked without a problem, and reading through the log helped me get a better idea for what was happening under the hood. 

I tested the workflow and it worked no problem! Now I'd like to be able to use my own FASTQs - I'll open a new issue for that.
